import {
	PUBLIC_APPWRITE_PROJECT_ID,
	PUBLIC_APPWRITE_ENDPOINT,
	PUBLIC_APPWRITE_DATABASE_MAIN_ID,
	PUBLIC_APPWRITE_DATABASE_MAIN_COLLECTION_USERS_ID,
	PUBLIC_APPWRITE_DATABASE_MAIN_COLLECTION_VOLUNTEER_TASKS_ID,
	PUBLIC_APPWRITE_STORAGE_BUCKET_APPROVAL_DOCUMENTS_ID,
	PUBLIC_APPWRITE_DATABASE_MAIN_COLLECTION_VOLUNTEER_REPORTS_ID,
	PUBLIC_APPWRITE_STORAGE_BUCKET_VOLUNTEER_DOCUMENTS_ID,
	PUBLIC_APPWRITE_DATABASE_MAIN_COLLECTION_INTEREST_SURVEY_RESPONSES_ID
} from '$env/static/public';
import { APPWRITE_API_KEY } from '$env/static/private';

// Contains private configuration values; do not pass to client
export const appwriteConfig = {
	endpoint: PUBLIC_APPWRITE_ENDPOINT,
	projectId: PUBLIC_APPWRITE_PROJECT_ID,
	apiKey: APPWRITE_API_KEY,
	databases: {
		main: {
			id: PUBLIC_APPWRITE_DATABASE_MAIN_ID,
			tables: {
				users: PUBLIC_APPWRITE_DATABASE_MAIN_COLLECTION_USERS_ID,
				volunteerTasks: PUBLIC_APPWRITE_DATABASE_MAIN_COLLECTION_VOLUNTEER_TASKS_ID,
				volunteerReports: PUBLIC_APPWRITE_DATABASE_MAIN_COLLECTION_VOLUNTEER_REPORTS_ID,
				interestSurveryResponses: PUBLIC_APPWRITE_DATABASE_MAIN_COLLECTION_INTEREST_SURVEY_RESPONSES_ID
			}
		}
	},
	storage: {
		approvalDocuments: PUBLIC_APPWRITE_STORAGE_BUCKET_APPROVAL_DOCUMENTS_ID,
		volunteerDocuments: PUBLIC_APPWRITE_STORAGE_BUCKET_VOLUNTEER_DOCUMENTS_ID
	}
} as const;
